### ISSUE TITLE
fix: standalone server.js crashes — Next.js 16.2.2 missing module + fallback should be next start

### ISSUE THREAD

**Issue by pitimon** [pitimon/cc-lens#92]
## Bug

`node bin/cli.js` crashes on standalone mode with Next.js 16.2.2:

```
Error: Cannot find module '../../client/components/app-router-headers'
Require stack:
- .next/standalone/node_modules/next/dist/server/app-render/work-unit-async-storage.external.js
```

## Root Cause

**Next.js 16.2.2 standalone output is incomplete** — it bundles `server.js` but the `app-router-headers` client module is not included in the standalone `node_modules/next/` directory. This is a known pattern with Next.js standalone + App Router.

## Additional Issue: Fallback is `next dev` instead of `next start`

**File:** `bin/cli.js:256-263`

When standalone fails, the else branch falls back to `next dev`:

```js
const child = useStandalone
  ? spawn(process.execPath, [standaloneServer], { ... })
  : spawn(process.execPath, [nextCli, "dev", ...], { ... });  // ← should be "start"
```

This negates the performance work from #78 — fallback should use `next start`, not `next dev`.

### Option A — Fix standalone by copying missing modules

```js
// After copyStandaloneAssets(), also copy the full next package
const nextSrc = path.join(CACHE_DIR, "node_modules", "next");
const nextDest = path.join(standaloneDir, "node_modules", "next");
fs.cpSync(nextSrc, nextDest, { recursive: true, force: true });
```

### Option B — Fall back to `next start` instead of `next dev`

```diff
- [nextCli, "dev", "--port", String(port), "--hostname", host],
+ [nextCli, "start", "--port", String(port), "--hostname", host],
```

### Option C — Disable standalone until Next.js fixes the bug

```diff
// next.config.ts
- output: "standalone",
+ // output: "standalone",  // disabled: Next.js 16.2.2 missing client modules
```

Use `next start` as primary (v0.4.4 approach) until Next.js resolves the standalone App Router issue.

**Recommended: Option B + C** — revert standalone, keep `next start` as stable default. Re-enable standalone when Next.js fixes the module bundling issue.

## Evidence

```
Error: Cannot find module '../../client/components/app-router-headers'
Node.js v22.18.0
Next.js 16.2.2 (Turbopack)
```

Server fell back to launchd-managed old version (v0.5.0) due to KeepAlive restart.

## Context

- Standalone introduced in #81 based on Next.js docs
- Known Next.js standalone + App Router issues exist upstream
- Related: #78 (dev→start), #81 (standalone)
